name: Lint n Test
on: [ push, pull_request ]
defaults:
  run:
    working-directory: datamanager/nodejs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
